[package]
name = "dp_main"
version = "0.3.0"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"

[dependencies]
num-bigint = "0.4.6"

[dependencies.dp_macro]
path = "../dp_lib"
